name: Gerar animação Pac-Man

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gerar gráficos Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "[email protected]"

      - name: Commit e push dos gráficos
        run: |
          git add -A output
          git commit -m "Atualizar gráficos Pac-Man [skip ci]" || echo "Sem alterações para commit"
          git push
